# Copyright  Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer.ibm.com:
    container_name: orderer.ibm.com
    image: hyperledger/fabric-orderer
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../crypto-config/ordererOrganizations/ibm.com/orderers/orderer.ibm.com/msp:/var/hyperledger/orderer/msp
    - ../crypto-config/ordererOrganizations/ibm.com/orderers/orderer.ibm.com/tls/:/var/hyperledger/orderer/tls
    ports:
      - 7050:7050

###################################################################
#   Insurer Org's members
# - assessor
# - officer
###################################################################
  
  assessor.insurer.com:
    container_name: assessor.insurer.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=assessor.insurer.com
      - CORE_PEER_ADDRESS=assessor.insurer.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=assessor.insurer.com:7051
      - CORE_PEER_LOCALMSPID=InsurerMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/insurer.com/peers/assessor.insurer.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/insurer.com/peers/assessor.insurer.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 8051:7051
      - 8053:7053

  officer.insurer.com:
    container_name: officer.insurer.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=officer.insurer.com
      - CORE_PEER_ADDRESS=officer.insurer.com:7051  
      - CORE_PEER_GOSSIP_BOOTSTRAP=officer.insurer.com:7051
      - CORE_PEER_LOCALMSPID=InsurerMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/insurer.com/peers/officer.insurer.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/insurer.com/peers/officer.insurer.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 9051:7051
      - 9053:7053

###################################################################
#   Repairer Org's members
# - shop1
###################################################################

  shop1.repairer.com:
    container_name: shop1.repairer.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=shop1.repairer.com
      - CORE_PEER_ADDRESS=shop1.repairer.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=shop1.repairer.com:7051
      - CORE_PEER_LOCALMSPID=RepairerMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/repairer.com/peers/shop1.repairer.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/repairer.com/peers/shop1.repairer.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 11051:7051
      - 11053:7053

###################################################################
#   Customer Org's members
# - john
###################################################################
  
  john.customer.com:
    container_name: john.customer.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=john.customer.com
      - CORE_PEER_ADDRESS=john.customer.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=john.customer.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=john.customer.com:7051      
      - CORE_PEER_LOCALMSPID=CustomerMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/customer.com/peers/john.customer.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/customer.com/peers/john.customer.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 21051:7051
      - 21053:7053
