# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  mafn:

services:
  # CAs
  ca.insurer.com:
    container_name: ca.insurer.com
    extends:
      file:  base/ca-base.yaml
      service: ca.insurer.com
    networks:
      - mafn

  ca.repairer.com:
    container_name: ca.repairer.com
    extends:
      file:  base/ca-base.yaml
      service: ca.repairer.com
    networks:
      - mafn

  ca.customer.com:
    container_name: ca.customer.com
    extends:
      file:  base/ca-base.yaml
      service: ca.customer.com
    networks:
      - mafn 

  # Orderer 
  orderer.ibm.com:
    container_name: orderer.ibm.com
    extends:
      file:   base/compose-base.yaml
      service: orderer.ibm.com
    networks:
      - mafn

  # Insurer Org's Peers
  officer.insurer.com:
    container_name: officer.insurer.com
    extends:
      file:  base/compose-base.yaml
      service: officer.insurer.com
    depends_on:
      - orderer.ibm.com
    networks:
      - mafn

  assessor.insurer.com:
    container_name: assessor.insurer.com
    extends:
      file:  base/compose-base.yaml
      service: assessor.insurer.com
    depends_on:
      - orderer.ibm.com
    networks:
      - mafn
  
  # Repairer Org's Peers
  shop1.repairer.com:
    container_name: shop1.repairer.com
    extends:
      file:  base/compose-base.yaml
      service: shop1.repairer.com
    depends_on:
      - orderer.ibm.com
    networks:
      - mafn

  # Customer Org's Peers
  john.customer.com:
    container_name: john.customer.com
    extends:
      file:  base/compose-base.yaml
      service: john.customer.com
    depends_on:
      - orderer.ibm.com
    networks:
      - mafn
  
  # CLI Container
  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=${CLI_LOGGING_LEVEL}
      - CORE_PEER_ID=cli
      - CORE_PEER_TLS_ENABLED=true
      # PoC specific env params below
      - CHANNEL_NAME=${CHANNEL_NAME}
      - CHAINCODE_NAME=${CHAINCODE_NAME}
      - CLAIM_KEY=${CLAIM_KEY}
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash -c './scripts/cli-script-e2e.sh; sleep 3'
    volumes:
        - /var/run/:/host/var/run/
        - ./chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.ibm.com
      - officer.insurer.com
      - assessor.insurer.com
      - shop1.repairer.com
      - john.customer.com
    networks:
      - mafn
